apiVersion: apps/v1
kind: Deployment
metadata:
  name: sahil-sample-deploy
  labels:
    app: sahil-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sahil-sample
  template:
    metadata:
      labels:
        app: sahil-sample
    spec:
      containers:
        - name: web
          image: nginx:stable
          ports:
            - containerPort: 80
